blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('<int:blog_id>', views.detail, name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),
    path('blog/', include('blog.urls'), name='blog')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def homepage(request):
    blogs = Blog.objects.all()
    context = {
        'blogs': blogs
    }
    return render(request, 'blog/homepage.html', context)

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    context = {
        'blog': blog
    }
    return render(request, 'blog/detail.html', context)

portfolio/views.py
from django.shortcuts import render
from .models import Project

def homepage(request):

    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    
    return render(request, 'portfolio/homepage.html', context)

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>{{ blog.title }}</h1>
    <h5>{{ blog.date|date:'M d, Y' }}</h5>
    <p>{{ blog.description }}</p>
{% endblock %}

blog/templates/blog/homepage.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>Blog Homepage</h1>
    
    <b>Total de Blogs: {{ blogs.count }}</b>

    {% for blog in blogs %}
        <h3><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h3>
        <h5>{{ blog.date|date:'M d, Y' }}</h5>
        <p>{{ blog.description|truncatechars:150 }}</p>
        <br>
    {% endfor %}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>Personal Portfolio</title>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Portfolio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
                        <a class="nav-link" href="{% url 'blog:homepage' %}">Blog</a>
                        <a class="nav-link" href="{% static 'portfolio/dummy.pdf' %}">PDF File</a>
                    </div>
                </div>
            </nav>

            {% block content %}
            {% endblock %}

            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>        
        </div>
    </body>
</html>

portfolio/templates/portfolio/homepage.html
{% extends 'portfolio/base.html' %}

{% block content %}
    {% load static %}

    <!--<a href="{% url 'blog:homepage' %}">Blogs</a>-->

    <div class="text-center">
        <img src="{% static 'portfolio/welcome.jpg' %}" alt="">
    </div>

    <!-- <a href="{% static 'portfolio/dummy.pdf' %}">PDF file</a> -->

    <div class="alert alert-primary" role="alert">
        <h1 class="text-center">Portfolio Homepage</h1>
    </div>

    <div class="row">
    {% for project in projects %}

        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <img src="{{ project.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    {% if project.url %}
                        <a href="{{ project.url }}" class="btn btn-primary">Visit Project</a>
                    {% endif %}
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>

{% endblock %}